# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'VagalumeFM' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VagalumeFM
  pod 'Firebase/Core', '~> 4.13.0'
  #pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'

  pod 'Firebase/Auth', '~> 4.13.0'
  pod 'Firebase/Crash'
  pod 'Fabric', '~> 1.7.2'
  pod 'Crashlytics', '~> 3.9.3'
  pod 'Firebase/Database'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'

  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  # pod 'lottie-ios', :path => '../node_modules/lottie-ios'
  # pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

end
